import app from 'flarum/forum/app';
import { extend } from 'flarum/common/extend';
import UserCard from 'flarum/forum/components/UserCard';
import type Mithril from 'mithril';

import { cssUrl, clampFocus, clampZoom } from '../common/util';
import prefetchImage from './prefetch';

/**
 * Paints the cover (with its focal point) onto every UserCard surface:
 *
 * - the user page hero,
 * - post hover cards      (className: UserCard--popover)   [setting-gated]
 * - fof/user-directory    (className: UserCard--directory) [setting-gated]
 *
 * fof/user-directory's cards subclass core's UserCard, so no extra
 * integration code is needed — the className tells the contexts apart.
 *
 * The image itself is painted by an injected .CoverStudio-cover child with
 * its own overflow clipping. The card must NOT be clipped (overflow: hidden
 * on the card would cut off dropdown menus inside the hero), but the zoom
 * transform makes the image layers extend past the card bounds — hence the
 * dedicated, clipped wrapper.
 */
export default function applyCoverToUserCards() {
  extend(UserCard.prototype, 'view', function (this: UserCard, vnode: Mithril.Vnode<Record<string, unknown>>) {
    const user = (this.attrs as { user?: import('flarum/common/models/User').default }).user;

    if (!user || !vnode?.attrs) return;

    const context = String((this.attrs as { className?: string }).className || '');
    const isPopover = context.includes('UserCard--popover');
    const isDirectory = context.includes('UserCard--directory');
    const isHero = !isPopover && !isDirectory;

    if (isPopover && !app.forum.attribute('tryhackx-cover-studio.show_on_popover')) return;
    if (isDirectory && !app.forum.attribute('tryhackx-cover-studio.show_on_directory')) return;

    // On the profile hero of an editable user, quietly warm the cache for the
    // editor source images so the position editors open without waiting
    // behind the page's post images.
    if (isHero) {
      if (user.canSetCover?.()) {
        prefetchImage(user.coverThumbUrl?.() || user.coverUrl?.());
      }

      if (user.canSetAvatarFocus?.() && app.forum.attribute('tryhackx-cover-studio.avatar_focus')) {
        prefetchImage(user.avatarOriginalUrl?.());
      }
    }

    let url = user.coverUrl?.();
    let x = clampFocus(Number(user.coverFocusX?.() ?? 50));
    let y = clampFocus(Number(user.coverFocusY?.() ?? 50));
    let zoom = clampZoom(Number(user.coverZoom?.() ?? 1));
    let isDefault = false;

    if (url) {
      // Smaller surfaces get the lightweight thumbnail generated by fof/upload.
      if ((isPopover || isDirectory) && user.coverThumbUrl?.()) {
        url = user.coverThumbUrl();
      }
    } else {
      const fallback = app.forum.attribute<string>('tryhackx-cover-studio.default_cover_url');

      if (!fallback) return;

      url = fallback;
      x = 50;
      y = 50;
      zoom = 1;
      isDefault = true;
    }

    const attrs = vnode.attrs as { className?: string; style?: Record<string, string> | false };

    const style = attrs.style && typeof attrs.style === 'object' ? attrs.style : (attrs.style = {});
    style['--cs-cover'] = cssUrl(url!);
    style['--cs-x'] = `${x}%`;
    style['--cs-y'] = `${y}%`;
    style['--cs-zoom'] = `${zoom}`;

    attrs.className =
      `${attrs.className || ''} CoverStudio-hasCover` +
      (zoom < 1 ? ' CoverStudio-zoomOut' : '') +
      (isDefault ? ' CoverStudio-defaultCover' : '');

    // Clipped image layer, inserted below the card content. The overlay child
    // spans the FULL card height (unlike .darkenBackground, which hugs the
    // bottom-pinned content on tall heroes), so the readability gradient runs
    // smoothly from the top edge instead of starting abruptly mid-cover.
    if (Array.isArray(vnode.children)) {
      vnode.children.unshift(
        m('div', { className: 'CoverStudio-cover', 'aria-hidden': 'true' }, m('div', { className: 'CoverStudio-cover-overlay' }))
      );
    }
  });
}
